### ISSUE TITLE
Calls to `listener` don't work in some cases

### ISSUE THREAD

**Issue by williamjacksn** [rmcauley/rainwave#87]
If a listener has rated a song on the DJ-only station, where `song_origin_sid == 0`, then calls to `listener` for that listener will fail.

    POST /api4/listener
    user_id=5049&key=REDACTED&id=11103

    {"api_info": {"exectime": 0.0507969856262207, "time": 1431973416.0}, "traceback": {"traceback": ["Traceback (most recent call last):\n", "  File \"/usr/lib/python2.7/dist-packages/tornado/web.py\", line 1346, in _when_complete\n    callback()\n", "  File \"/usr/lib/python2.7/dist-packages/tornado/web.py\", line 1367, in _execute_method\n    self._when_complete(method(*self.path_args, **self.path_kwargs),\n", "  File \"/opt/rainwave/api_requests/listener.py\", line 72, in post\n    user['rating_completion'][row['sid']] = math.ceil(float(row['ratings']) / float(playlist.num_songs[row['sid']]) * 100)\n", "KeyError: 0\n"]}, "error": {"text": "KeyError(0,)", "tl_key": "internal_error", "code": 500}}

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _when_complete
        callback()
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1367, in _execute_method
        self._when_complete(method(*self.path_args, **self.path_kwargs),
      File "/opt/rainwave/api_requests/listener.py", line 72, in post
        user['rating_completion'][row['sid']] = math.ceil(float(row['ratings']) / float(playlist.num_songs[row['sid']]) * 100)
    KeyError: 0

**Comment by williamjacksn** [comment]
I manually deleted the ratings for the DJ-only songs from the database a moment ago to temporarily relieve the problem.
